# ========================================
# Datasource
# ========================================

quarkus.datasource.db-kind=h2


# ========================================
# Development - PostgreSQL
# ========================================

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${DB_DEVELOPMENT_USERNAME}
%dev.quarkus.datasource.password=${DB_DEVELOPMENT_PASSWORD}
%dev.quarkus.datasource.jdbc.url=${DB_DEVELOPMENT_URL}

%dev.quarkus.hibernate-orm.database.generation=update


# ========================================
# Test - H2
# ========================================

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:right_time

%test.quarkus.hibernate-orm.database.generation=drop-and-create